---
driver:
  name: docker
  use_sudo: false
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec
  # sudo: false # if 'true' (default) inSpec will run tests as 'root', rather than 'kitchen'
  format: doc
  sudo_command: '. /etc/profile;'


platforms:
  - name: ubuntu-14.04
    driver_config:
      instance_name: metaphlan2-ubuntu1404
  # - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[metaphlan2::default]
    attributes:
